services:
  - type: web
    name: flight-chess-share-fei
    runtime: node
    rootDir: flight-chess-share
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
